version: "3.8"

services:

  db:
    image: postgres:13.2
    restart: always
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 25

  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    container_name: pgadmin
    hostname: pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_ENABLE_TLS: null
#      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db:pgsql-server

volumes:
  db-data:
  pgadmin-data:
