version: "3.9"

services:
  db:
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db_import:/docker-entrypoint-initdb.d
  pgadmin:
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./db_config:/import_db
